ports:
  - port: 4040 # pyspark UI
    onOpen: notify
tasks:
  - name: setup
    init: |
      python3 -m venv venv
    command: |
      echo "source $(pwd)/venv/bin/activate" >> ~/.bashrc
      source venv/bin/activate
  - name: Gitpod config (browser open, workspace bin path)
    init: |
      mkdir -p /workspace/bin
      cat > /workspace/bin/open.sh <<'EOF'
      #!/bin/bash
      exec gp preview --external "$@"
      EOF
      chmod +x /workspace/bin/open.sh
    command: |
      sudo update-alternatives --install /usr/bin/www-browser www-browser /workspace/bin/open.sh 100
      exit
image:
  file: .gitpod.comment_Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true