version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
  deploy:
    commands:
      - cd infrastructure
      - terraform init
      - terraform apply -auto-approve

