version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip3 install pytest requests==2.31.0  pyspark==3.2.1
  build:
    commands:
      - echo $JAVA_HOME
      - python -m pytest --junitxml=test_reports/test_report

reports:
  pytest_reports:
    files:
      - test_report
    base-directory: test_reports
    file-format: JUNITXML