version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip3 install pytest requests==2.31.0  pyspark==3.2.1 boto3==1.29.7  botocore==1.32.7 pytz
  build:
    commands:
      - echo $JAVA_HOME
      - ls
      - python3 -m pytest tests/integratedexercise/transform_test.py
#      - python -m pytest --junitxml=test_reports/test_report

reports:
  pytest_reports:
    files:
      - test_report
    base-directory: test_reports
    file-format: JUNITXML